# Generated by Django 4.2.6 on 2023-10-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogapp',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
