# Generated by Django 4.2.6 on 2023-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogapp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
