# Generated by Django 4.2.6 on 2023-10-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blogapp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogapp',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
