# Generated by Django 4.2.6 on 2023-10-31 14:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blogapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogapp',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
